### ISSUE TITLE
Hey Fryy!

### ISSUE THREAD

**Issue by bojidar-bg** [KOBUGE-Games/Yatzy#1]
Welcome back :wink: (might join the chat tonight, will see)

**Comment by akien-mga** [comment]
Now that's a useful issue @bojidar-bg :P

I'll test the game tonight :) @fry- It looks like your commit is not attributed to your GitHub account, most likely because it uses a different email address which is not registered for your account. Just FYI, you might have done that on purpose :)

**Comment by mamarilmanson** [comment]
And this repo is????? 

sorry I'm not aware... :)

**Comment by bojidar-bg** [comment]
@mamarilmanson That's some Yatzee® remake.

**Comment by mamarilmanson** [comment]
ohhh... ok... :)

**Comment by ObaniGemini** [comment]
NIce, it's been a long time I haven't seen him too :)

**Comment by est31** [comment]
Hi!

**Comment by fry-** [comment]
@akien-mga oh you are right, I think it is because I used git the first time on this laptop and forgot about configuring :smile: Thanks for mentioning it. I thought by entering my username and password it would automatically link it to my account^^
@bojidar-bg @ObaniGemini @est31 Hi guys :) nice to see you!
